/* tslint:disable */
/* eslint-disable */
/*
Swagger CrowdSec

CrowdSec local API

The version of the OpenAPI document: 1.0.0
Contact: contact@crowdsec.net

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/


export * from './api/bouncers-api';
export * from './api/watchers-api';

