/*
Swagger CrowdSec

CrowdSec local API

The version of the OpenAPI document: 1.0.0
Contact: contact@crowdsec.net

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  BouncersApi,
  WatchersApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { CrowdSecCustom } from "./client-custom";

export class CrowdSec extends CrowdSecCustom {
  readonly bouncers: BouncersApi;
  readonly watchers: WatchersApi;

  constructor(configurationParameters: ConfigurationParameters = {}) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.bouncers = new BouncersApi(configuration);
    this.watchers = new WatchersApi(configuration);
  }

}
