/*
Swagger CrowdSec

CrowdSec local API

The version of the OpenAPI document: 1.0.0
Contact: contact@crowdsec.net

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Decision } from './decision';
import { Event } from './event';
import { MetaInner } from './meta-inner';
import { Source } from './source';

/**
 * 
 * @export
 * @interface Alert
 */
export interface Alert {
    /**
     * only relevant for GET, ignored in POST requests
     * @type {number}
     * @memberof Alert
     */
    'id'?: number;
    /**
     * only relevant for LAPI->CAPI, ignored for cscli->LAPI and crowdsec->LAPI
     * @type {string}
     * @memberof Alert
     */
    'uuid'?: string;
    /**
     * only relevant for LAPI->CAPI, ignored for cscli->LAPI and crowdsec->LAPI
     * @type {string}
     * @memberof Alert
     */
    'machine_id'?: string;
    /**
     * only relevant for GET, ignored in POST requests
     * @type {string}
     * @memberof Alert
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof Alert
     */
    'scenario': string;
    /**
     * 
     * @type {string}
     * @memberof Alert
     */
    'scenario_hash': string;
    /**
     * 
     * @type {string}
     * @memberof Alert
     */
    'scenario_version': string;
    /**
     * a human readable message
     * @type {string}
     * @memberof Alert
     */
    'message': string;
    /**
     * 
     * @type {number}
     * @memberof Alert
     */
    'events_count': number;
    /**
     * 
     * @type {string}
     * @memberof Alert
     */
    'start_at': string;
    /**
     * 
     * @type {string}
     * @memberof Alert
     */
    'stop_at': string;
    /**
     * 
     * @type {number}
     * @memberof Alert
     */
    'capacity': number;
    /**
     * 
     * @type {string}
     * @memberof Alert
     */
    'leakspeed': string;
    /**
     * 
     * @type {boolean}
     * @memberof Alert
     */
    'simulated': boolean;
    /**
     * the Meta of the events leading to overflow
     * @type {Array<Event>}
     * @memberof Alert
     */
    'events': Array<Event>;
    /**
     * 
     * @type {boolean}
     * @memberof Alert
     */
    'remediation'?: boolean;
    /**
     * 
     * @type {Array<Decision>}
     * @memberof Alert
     */
    'decisions'?: Array<Decision>;
    /**
     * 
     * @type {Source}
     * @memberof Alert
     */
    'source': Source;
    /**
     * the Meta data of the Alert itself
     * @type {Array<MetaInner>}
     * @memberof Alert
     */
    'meta'?: Array<MetaInner>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Alert
     */
    'labels'?: Array<string>;
}

