/*
Swagger CrowdSec

CrowdSec local API

The version of the OpenAPI document: 1.0.0
Contact: contact@crowdsec.net

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Decision } from './decision';

/**
 * 
 * @export
 * @interface DecisionsStreamResponse
 */
export interface DecisionsStreamResponse {
    /**
     * 
     * @type {Array<Decision>}
     * @memberof DecisionsStreamResponse
     */
    'new'?: Array<Decision>;
    /**
     * 
     * @type {Array<Decision>}
     * @memberof DecisionsStreamResponse
     */
    'deleted'?: Array<Decision>;
}

