/*
Swagger CrowdSec

CrowdSec local API

The version of the OpenAPI document: 1.0.0
Contact: contact@crowdsec.net

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Decision
 */
export interface Decision {
    /**
     * (only relevant for GET ops) the unique id
     * @type {number}
     * @memberof Decision
     */
    'id'?: number;
    /**
     * only relevant for LAPI->CAPI, ignored for cscli->LAPI and crowdsec->LAPI
     * @type {string}
     * @memberof Decision
     */
    'uuid'?: string;
    /**
     * the origin of the decision : cscli, crowdsec
     * @type {string}
     * @memberof Decision
     */
    'origin': string;
    /**
     * the type of decision, might be \'ban\', \'captcha\' or something custom. Ignored when watcher (cscli/crowdsec) is pushing to APIL.
     * @type {string}
     * @memberof Decision
     */
    'type': string;
    /**
     * the scope of decision : does it apply to an IP, a range, a username, etc
     * @type {string}
     * @memberof Decision
     */
    'scope': string;
    /**
     * the value of the decision scope : an IP, a range, a username, etc
     * @type {string}
     * @memberof Decision
     */
    'value': string;
    /**
     * the duration of the decisions
     * @type {string}
     * @memberof Decision
     */
    'duration': string;
    /**
     * the date until the decisions must be active
     * @type {string}
     * @memberof Decision
     */
    'until'?: string;
    /**
     * 
     * @type {string}
     * @memberof Decision
     */
    'scenario': string;
    /**
     * true if the decision result from a scenario in simulation mode
     * @type {boolean}
     * @memberof Decision
     */
    'simulated'?: boolean;
}

