/*
Swagger CrowdSec

CrowdSec local API

The version of the OpenAPI document: 1.0.0
Contact: contact@crowdsec.net

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DeleteAlertsResponse
 */
export interface DeleteAlertsResponse {
    /**
     * number of deleted alerts
     * @type {string}
     * @memberof DeleteAlertsResponse
     */
    'nbDeleted'?: string;
}

