/*
Swagger CrowdSec

CrowdSec local API

The version of the OpenAPI document: 1.0.0
Contact: contact@crowdsec.net

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MetaInner } from './meta-inner';

/**
 * 
 * @export
 * @interface Event
 */
export interface Event {
    /**
     * 
     * @type {string}
     * @memberof Event
     */
    'timestamp': string;
    /**
     * the Meta data of the Alert itself
     * @type {Array<MetaInner>}
     * @memberof Event
     */
    'meta': Array<MetaInner>;
}

