/*
Swagger CrowdSec

CrowdSec local API

The version of the OpenAPI document: 1.0.0
Contact: contact@crowdsec.net

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface MetaInner
 */
export interface MetaInner {
    /**
     * 
     * @type {string}
     * @memberof MetaInner
     */
    'key'?: string;
    /**
     * 
     * @type {string}
     * @memberof MetaInner
     */
    'value'?: string;
}

