/*
Swagger CrowdSec

CrowdSec local API

The version of the OpenAPI document: 1.0.0
Contact: contact@crowdsec.net

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Software version info (so we can warn users about out-of-date software). The software name and the version are \"guessed\" from the user-agent
 * @export
 * @interface MetricsAgentInfo
 */
export interface MetricsAgentInfo {
    /**
     * software version
     * @type {string}
     * @memberof MetricsAgentInfo
     */
    'version'?: string;
    /**
     * name of the component
     * @type {string}
     * @memberof MetricsAgentInfo
     */
    'name'?: string;
    /**
     * last agent update date
     * @type {string}
     * @memberof MetricsAgentInfo
     */
    'last_update'?: string;
    /**
     * last agent push date
     * @type {string}
     * @memberof MetricsAgentInfo
     */
    'last_push'?: string;
}

