/*
Swagger CrowdSec

CrowdSec local API

The version of the OpenAPI document: 1.0.0
Contact: contact@crowdsec.net

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MetricsAgentInfo } from './metrics-agent-info';
import { MetricsBouncerInfo } from './metrics-bouncer-info';

/**
 * 
 * @export
 * @interface Metrics
 */
export interface Metrics {
    /**
     * the local version of crowdsec/apil
     * @type {string}
     * @memberof Metrics
     */
    'apil_version': string;
    /**
     * 
     * @type {Array<MetricsBouncerInfo>}
     * @memberof Metrics
     */
    'bouncers': Array<MetricsBouncerInfo>;
    /**
     * 
     * @type {Array<MetricsAgentInfo>}
     * @memberof Metrics
     */
    'machines': Array<MetricsAgentInfo>;
}

