/*
Swagger CrowdSec

CrowdSec local API

The version of the OpenAPI document: 1.0.0
Contact: contact@crowdsec.net

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Source
 */
export interface Source {
    /**
     * the scope of a source : ip,range,username,etc
     * @type {string}
     * @memberof Source
     */
    'scope': string;
    /**
     * the value of a source : the ip, the range, the username,etc
     * @type {string}
     * @memberof Source
     */
    'value': string;
    /**
     * provided as a convenience when the source is an IP
     * @type {string}
     * @memberof Source
     */
    'ip'?: string;
    /**
     * provided as a convenience when the source is an IP
     * @type {string}
     * @memberof Source
     */
    'range'?: string;
    /**
     * provided as a convenience when the source is an IP
     * @type {string}
     * @memberof Source
     */
    'as_number'?: string;
    /**
     * provided as a convenience when the source is an IP
     * @type {string}
     * @memberof Source
     */
    'as_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Source
     */
    'cn'?: string;
    /**
     * 
     * @type {number}
     * @memberof Source
     */
    'latitude'?: number;
    /**
     * 
     * @type {number}
     * @memberof Source
     */
    'longitude'?: number;
}

