/*
Swagger CrowdSec

CrowdSec local API

The version of the OpenAPI document: 1.0.0
Contact: contact@crowdsec.net

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * the response of a successful authentication
 * @export
 * @interface WatcherAuthResponse
 */
export interface WatcherAuthResponse {
    /**
     * 
     * @type {number}
     * @memberof WatcherAuthResponse
     */
    'code'?: number;
    /**
     * 
     * @type {string}
     * @memberof WatcherAuthResponse
     */
    'expire'?: string;
    /**
     * 
     * @type {string}
     * @memberof WatcherAuthResponse
     */
    'token'?: string;
}

